name: drugpack
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.1.5
  retrofit: ^4.1.0
  dio: ^5.4.2+1
  go_router: ^13.2.0
  collection: ^1.17.2
  rxdart: ^0.27.7
  flutter_local_notifications: ^17.0.0
  smooth_page_indicator: ^1.1.0
  http: ^1.1.0
  easy_localization: ^3.0.5
  flutter_secure_storage: ^4.2.1
  hexcolor: ^3.0.1
  json_serializable: ^6.7.1
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^8.1.0
  freezed: ^2.4.2
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  flutter_gen: ^5.3.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/translations/